server:
    port: 8080
spring: 
  datasource:
    password: 
    url: jdbc:h2:file:~/desktop/testdb
    username: sa
    
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

